### ISSUE TITLE
老哥有空也把重启的bug也修一下吧

### ISSUE THREAD

**Issue by Rtc73v** [mingxiaoyu/R1-Plus-LTS#1]
昨天拿你的这个源https://github.com/mingxiaoyu/immortalwrt/tree/r1lts  自己编译了一个固件，
目前作为旁路由使用是没啥问题了，就发现重启的不了的毛病还在，其他的就没发现有什么毛病了，满足日常使用了

不知道官方这个能抄个作业么
https://github.com/orangepi-xunlong/openwrt/commit/01c00f93f8064c256c4cce9fd559729ee5e2dc95

**Comment by mingxiaoyu** [comment]
@Rtc73v 就是按重启 重启不了？我不确定这个patch是否可以。。这段时间都是调整代码 好满足大佬的要求。明天中午吃完午饭看看吧。年末了，太忙了

**Comment by Rtc73v** [comment]
对，就是在网页上点重启，或者在终端reboot，结果都是设备失联，然后再起不能，只能通过断电来启动，应该是百分百复现，老哥有空的话就看看，一般也没重启的需求

**Comment by mingxiaoyu** [comment]
@Rtc73v 我多次测试，没这个问题吧。不过那个补丁是可以加入了，编译没问题

**Comment by Rtc73v** [comment]
那就等并入主线了

**Comment by mingxiaoyu** [comment]
@Rtc73v 云编译，然后跑一天试试，在给天灵大佬 看看

**Comment by Rtc73v** [comment]
可能你这个云编译会失败了。
WARNING: Makefile 'package/feeds/luci/luci-app-firewall/Makefile' has a dependency on 'uci-firewall', which does not exist
报这个错应该出不了固件
估计得重行拉一下源码

**Comment by mingxiaoyu** [comment]
我的wan貌似坏了。。。。。

**Comment by mingxiaoyu** [comment]
@Rtc73v 我没设备了，淘宝客服说要log. 我要晚上才能给。 周末他们不上班。我麻了，裂了。

**Comment by Rtc73v** [comment]
呃，这也坏的太快了，只用lan口就是eth1试试，如果能进web页面，然后wan和wan6删除，把eth0并入br-lan里面，关闭dhcp，做旁路由，如果网线插在lan能正常上网，再把电脑插在wan口上，看看能不能用，

**Comment by mingxiaoyu** [comment]
@Rtc73v 不用那么麻烦，wan 链接 猫的 灯都不亮，一点亮都没有。

**Comment by Rtc73v** [comment]
不一定吧，可能是网卡没启动，所以不亮

**Comment by mingxiaoyu** [comment]
@Rtc73v  已经申请换货了。目测一周内没设备。你有空可以试试。今天编译的吧。没什么问题 我就试试PR

**Comment by Rtc73v** [comment]
明天试试看再回复你

**Comment by Rtc73v** [comment]
没发现什么问题，重启依旧失效

**Comment by mingxiaoyu** [comment]
@Rtc73v 我怀疑是卡的问题。你如果可以编译。。把那个补丁 直接复制进入就可以。。我的设备已经在寄回去的路上了。。。来回真的要快一周。

**Comment by Rtc73v** [comment]
晚点我再编译一个好了

**Comment by mingxiaoyu** [comment]
@Rtc73v  我的卡是class 4的辣鸡卡。也许是我卡慢 。不需要这个patch去延迟

**Comment by Rtc73v** [comment]
我的是闪迪的A1官方店打包买的，其他的系统打了补丁就是正常的了，这个测一下看看

**Comment by Rtc73v** [comment]
试了几次，貌似没用。。。。。
我是直接在target/linux/rockchip/patches-5.10/目录里面
wget https://raw.githubusercontent.com/orangepi-xunlong/openwrt/01c00f93f8064c256c4cce9fd559729ee5e2dc95/target/linux/rockchip/patches-5.4/809-Fix-reboot-with-UHS-cards.patch
然后进行二次编译的，然后重新刷入新squashfs格式的包。
加个补丁应该没必要全新编译吧。

**Comment by mingxiaoyu** [comment]
> 试了几次，貌似没用。。。。。 我是直接在target/linux/rockchip/patches-5.10/目录里面 wget https://raw.githubusercontent.com/orangepi-xunlong/openwrt/01c00f93f8064c256c4cce9fd559729ee5e2dc95/target/linux/rockchip/patches-5.4/809-Fix-reboot-with-UHS-cards.patch 然后进行二次编译的，然后重新刷入新squashfs格式的包。 加个补丁应该没必要全新编译吧。

一般不需要。我一般都是最小编译。几分钟就可以了。嘻嘻

**Comment by mingxiaoyu** [comment]
@Rtc73v 最新版的编译，我已经加上了官方那个补丁了

**Comment by Rtc73v** [comment]
今天板子好像自己重启了一次，没有设置自动重启，明明我手动都是失败的，观察一段时间再看吧。
等你并入主线我再折腾了，开摆

**Comment by mingxiaoyu** [comment]
@Rtc73v 求测试下 我新编译的。。。我不知道是换的新的 挑卡还是怎么。。

**Comment by Rtc73v** [comment]
开不了机？

**Comment by mingxiaoyu** [comment]
@Rtc73v  官方的没问题。。这我编译的 ttl 看了下 。经常卡一半。。偶尔能成功一次

**Comment by Rtc73v** [comment]
下午我测一下

**Comment by Rtc73v** [comment]
1.22的squashfs固件正常开机，重启也正常，
我自编译一个用用看

**Comment by mingxiaoyu** [comment]
。。。看来换了个挑卡的回来。。。。我去。谢谢了

**Comment by mingxiaoyu** [comment]
@Rtc73v 大概率是不会进主线了。 随便问下，你用docker 不？用？没问题？

**Comment by Rtc73v** [comment]
docker会影响udp，我没编译进去
有什么问题？

**Comment by mingxiaoyu** [comment]
@Rtc73v  一用docker就裂。。。不知道为什么？微信不？加一个交流交流

**Comment by Rtc73v** [comment]
TG聊

**Comment by sf6472** [comment]
我用 02.02 ext4 系统似乎没有这种问题

**Comment by mingxiaoyu** [comment]
@471654852 看卡和机子。我第一个机子 什么事都没。网卡不小心被我弄坏了。换了个新的。。。有点小问题

**Comment by mingxiaoyu** [comment]
体质差的 不要随便超频。。例如我。。。。。。。
现在应该算是修好了
