### ISSUE TITLE
大佬能不能出个精简版的

### ISSUE THREAD

**Issue by ma1ware01** [mingxiaoyu/R1-Plus-LTS#2]
之前用别的版本，基本一天重启几次，大佬编译的这个版本用了几天一次都没重启过，十分稳定，但是能不能出个精简版的，只带基础功能(ssrp & flow offloading)的版本。

**Comment by mingxiaoyu** [comment]
最多出一个不带dokcer的。 这个也是计划内的事情。时间有限。
我不想重复N1的原创被喷抄袭，所以闭源了。

**Comment by mingxiaoyu** [comment]
已经有个小小精简版了
