### ISSUE TITLE
请教下R1P LTS的软路由后台进不去

### ISSUE THREAD

**Issue by jwdeng** [mingxiaoyu/R1-Plus-LTS#4]
固件版本
[r1lts-2022.07.01-1337](https://github.com/mingxiaoyu/R1-Plus-LTS/releases/tag/r1lts-2022.07.01-1337)
(with docker版固件)

我这边设置的路由器后台地址为8.1,有加登录密码
前6天运行没问题,第七天的凌晨0点就断掉了(网络也无法访问)
早上起床我重启了一下路由,能正常上网,但无法访问8.1路由器后台
第一次登录8.1时显示
 error loading module 'luci.controller.banip' from file '/usr/lib/lua/luci/controller/banip.lua':
关机拔卡重插后,第二次登录时显示
Bad Gateway
The process did not produce any response

虽然都访问不了路由器后台,但都能正常上网

请问博主能不能指点下我这边可能存在的问题点和解决方法?
路由器就挂了一个docker青龙,一个去广告,一个网易云音乐,KMS,以及open clash

**Comment by jwdeng** [comment]
补: 我这边用AP路由器接出来一根网线(DHCP) 连到软路由上(R1PLTS),同样访问8.1后台,显示
/usr/lib/lua/luci/ccache.lua:70: error loading module 'luci.controller.adblock' from file '/usr/lib/lua/luci/controller/adblock.lua':
	/usr/lib/lua/luci/controller/adblock.lua:27: 'end' expected (to close 'function' at line 17) near '<eof>'
stack traceback:
	[C]: in function 'loader'
	/usr/lib/lua/luci/ccache.lua:70: in function </usr/lib/lua/luci/ccache.lua:61>
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1105: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:1205: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:693: in function 'menu_json'
	/usr/lib/lua/luci/dispatcher.lua:794: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>
看名字应该是广告拦截固件启动错误

**Comment by jwdeng** [comment]
重新安装解决了,还有IP地址是固定的2.1,修改了只能生效一次,下次断电重启后又恢复了8.1

**Comment by mingxiaoyu** [comment]
估计你的卡有坏道？推荐用默认的bootstrap 的主题

**Comment by jwdeng** [comment]
> 估计你的卡有坏道？推荐用默认的bootstrap 的主题

也有可能, 主题是默认主题,而且我这边没有其他能修改的主题()argon主题设置为跟随系统)
我现在能正常使用我就不管,如果几天后挂了,我再换TF卡试试, 感谢作者提供的固件

**Comment by mingxiaoyu** [comment]
> > 估计你的卡有坏道？推荐用默认的bootstrap 的主题
> 
> 也有可能, 主题是默认主题,而且我这边没有其他能修改的主题()argon主题设置为跟随系统) 我现在能正常使用我就不管,如果几天后挂了,我再换TF卡试试, 感谢作者提供的固件

argon 这个主题有时候莫名其妙会出问题。
